### ISSUE TITLE
Sent 0 MTN but no error thrown

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#102]
Comments from user:

- Sent 0 MTN to 0xf0999743292b647eee057e12ce2cd23174f26b80
- no error thrown, or message stating user cannot send 0 tokens
- In checking the transaction history, it says I sent 0 ETH to a different address than Greer's address. The address it says I sent 0 MTN to is 0x4c00f8ec2d4fc3d9cbe4d7bd04d80780d5cae77f. TXID 0x20d9f6a5cf4f7b0be5dcfbca368b1fc627addd80264a55d9b8a9f9e6d5a2e002 Block 456294

**Comment by pablen** [comment]
Related to #46.

**Comment by ianaya89** [comment]
@filcap According to contracts send 0 MTN is a valid option so we are allowing that. 
We are improving the tx history messages for those cases

**Comment by filcap** [comment]
OK, lets discuss on our call today if we want the contracts to throw on 0 transfers.  Adding @twleung

**Comment by ianaya89** [comment]
@filcap According to MET contracts behaviour, this is not an issue. Can you confirm that with NA team?

**Comment by gabmontes** [comment]
@filcap last item solved in #155.
