### ISSUE TITLE
Unhandled Promise Rejection Popups when open a long time

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#104]
Getting Unhandled Promise rejection popups in the following scenarios

- Leaving wallet open for a long time
- Network connectivity changes

Also when internet connection drops, unable to reload wallet after reconnection, gets stuck on contacting network message

**Comment by gabmontes** [comment]
@filcap this is related to issue #22. Will retest after the fix is merged.
