### ISSUE TITLE
Missing MTN to address

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#113]
Version: 0.5.0

Sent 5 MTN to an address using 0.4.0 wallet. When I loaded 0.5.0 wallet, the MTN transaction is missing. Unfortunately I do not have the original screenshot of the transactions. However, I listed the transaction issue as part of line #69  in this spreadsheet

"Transaction sent to: 0xf0999743292b647eee057e12ce2cd23174f26b80
Missing Transaction 5 MTN -- was originally confirmed on 0.4.0 wallet, but not listed on 0.5.0 wallet  0xb16cd0e49a20a47a0ce31c1e366640ba0a1ebc99681eaf5fde53a8683a2355ec / block 447036 "

**Comment by ianaya89** [comment]
Expected behaviour, wallets were using different contract addresses.
