### ISSUE TITLE
Recover wallet forces you to use the newly created password

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#117]
After eliminating the 'Settings' file (rm ~/Library/Application\ Support/metronome-desktop-wallet/Settings), use must re-register with a new password, then click Tools to recover old wallet. Using old phrases, the NEW password must be used in lieu of the old password. 

Expect that user would need to provide the original password paired with the original recovery words

**Comment by ianaya89** [comment]
Not applicable, the password is not related to the private key or mnemonic generation
