### ISSUE TITLE
Failed Transactions were once pending txns

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#138]
Version 0.6.0

Send .00000001 ETH or MTN for a few days the transactions were pending now they are marked as Failed.

"AMOUNT 1e-8 ETH
TYPE Auction
CONFIRMATIONS 30267
GAS USED 200000
TRANSACTION HASH 0x1d72259f280075d5347ef070a03bd630492e33502079304c62d6d08cb316e1b1
BLOCK NUMBER 463665"

**Comment by gabmontes** [comment]
@filcap something went wrong with that transaction. Traces show it finished with "Bad instruction".

Can you please check on the contract code side what could have happened?

**Comment by filcap** [comment]
Will do, i saw an issue logged for it, i assigned to myself and will check

**Comment by ianaya89** [comment]
Not able to reproduce
