### ISSUE TITLE
Error: Gas price too low on conversion

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#156]
Version 0.6.0

Attempt to use the Converter while you have a transaction in the queue (send yourself/someone ETH/MTN, use the Converter, etc.)

<red text> "Returned error: Transaction gas price is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce."

**Comment by ianaya89** [comment]
Related to #85
