### ISSUE TITLE
Attempting to Convert too low USD

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#157]
Use the Converter. Attempt to convert a very small amount of USD (0.0001). It auto-populates the ETH field.

<orange text> "Invalid amount" under ETH only, also "Amount (ETH)" is in orange text and the ETH entry box has an orange underline.

Expected to see Help text about minimum USD/ETH. Also should be clear this applies to the ETH and USD amounts instead of just the ETH.

**Comment by pablen** [comment]
Nice catch! this is caused by the exponential notation being considered invalid by the input field. This will be fixed in the next release.
