### ISSUE TITLE
After my first three buy transactions, my MTN balance still shows zero

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#17]
I did three transactions
- 3 ETH -> 909090 MTN
- 2 ETH -> 606060 MTN
- 1 ETH -> 303030 MTN

I can see them in Transactions View of my Wallet, but above still showing 0 MTN balance

**Comment by gabmontes** [comment]
@filcap this could be related to using different version of contracts. If you used the previous version of the app or manually reconfigured the app settings, that could happen.

Please remove the settings file, try again and update the ticket.

See: https://github.com/MetronomeToken/metronome-desktop-wallet#development-notes

**Comment by filcap** [comment]
I removed the file.  Restarted the app.  Initially it had me create a new account, but then i went to tools and recovered my old account, but still showing 0 balance.

But when i started a new auction buy, the new transaction is now showing up, and now i  see a balance of 1.74 MTN :)

I'm now getting a bunch of red messages appear at the top Could not sync to latest block.  Seem to appear in bunches of 3 to 4 every few seconds.

**Comment by gabmontes** [comment]
@filcap thanks for the info. Will close this issue and will open a new one to track the "Could not sync to latest block" message.
