### ISSUE TITLE
Unhandled Promise Rejection Error

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#18]
With the app open and not doing anything, some background process triggered a pop up with the error Unhandled Promise Rejection Error.  

Unhandled Promise Rejection
Error: read ETIMEDOUT
<img width="1213" alt="screen shot 2018-02-15 at 4 21 05 pm" src="https://user-images.githubusercontent.com/24193763/36287857-5971c570-126c-11e8-8b2c-1829ae9256a1.png">

**Comment by ianaya89** [comment]
Related to #22
