### ISSUE TITLE
Send MTN to another MTN Wallet

### ISSUE THREAD

**Issue by filcap** [autonomoussoftware/metronome-wallet-desktop#19]
I tried to Send MTN to another users MTN wallet.  Since it was during initial auction period i was expecting it to error out, but it was accepted.   But looks like my balance didnt update, still says 0 MTN which is expected.

**Comment by gabmontes** [comment]
@filcap what version of the wallet are you using? v0.3.0 has disabled the send MTN tab during the initial auction. Please confirm.

You can also Metronome-Wallet/About and see what version you are running.

**Comment by filcap** [comment]
I'm using Version 0.3.0.151

**Comment by ianaya89** [comment]
@filcap Can you confirm if this issue is still happening in the latest version?

**Comment by gabmontes** [comment]
Not able to replicate in v0.6/0.7. Closing.
