### ISSUE TITLE
Price is not decreasing in DSL

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome-wallet-desktop#201]
Price does not decrease in daily auction lower than ISA floor price.

**Comment by ianaya89** [comment]
@Dareknotderek can you please specify the meanings of DSL and ISA?

**Comment by Dareknotderek** [comment]
@ianaya89 Daily Supply Lost and Initial Supply Auction (sorry)

**Comment by ianaya89** [comment]
@Dareknotderek makes sense. Thanks!

**Comment by gabmontes** [comment]
@Dareknotderek this is not a behavior the wallet manages but is directly taken from the auction contract. Please open an issue in https://github.com/autonomoussoftware/metronome describing the observed and the expected behavior.

**Comment by Dareknotderek** [comment]
Understood. Thanks.
