### ISSUE TITLE
Issue in updating URL in setting

### ISSUE THREAD

**Issue by patidarmanoj10** [autonomoussoftware/metronome-wallet-desktop#21]
I am stuck after I updated URL in setting to connect my local blockchain . if I enter wrong URL or somehow not able to connect local chain, I get error on login, which is fine But main issue is I can not update that URL again to enter correct URL.  I uninstalled wallet again from my laptop and installed new copy but still same error.  . I am stuck now can not use wallet anymore.  is there any way clean it up and install again ?  I am using mac.

Unhandled Promise Rejection
Error: connection not open
    at WebsocketProvider.send (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/web3-providers-ws/src/index.js:219:18)
    at Timeout._onTimeout (/Applications/Metronome Wallet.app/Contents/Resources/app.asar/node_modules/web3-providers-ws/src/index.js:204:19)

**Comment by ianaya89** [comment]
We are aware of this issue and it is documented in the changelog as a "known issue".
You can change that setting manually while we add the proper handler for this situation.

To do that, you can edit the following file: `~/Library/Application\ Support/metronome-desktop-wallet/Settings`.

Look for property `websocketApiUrl` and update the value to a valid eth node url.

**Comment by ianaya89** [comment]
Related to #22
