### ISSUE TITLE
Converter calls are not working.

### ISSUE THREAD

**Issue by ianaya89** [autonomoussoftware/metronome-wallet-desktop#26]
- [x] Enable converter button
- [x] Contract call for ETH>MET
- [x] Contract call for MET>ETH
- [x] Display ETH>MET in txs row
- [x] Display MET approval and MET>ETH in txs row

**Comment by filcap** [comment]
it is expected for the converter calls to fail during initial auction.  If its during dailies, let me know and i can trouble shoot the smart contract.
