### ISSUE TITLE
Update "Terms & Conditions" URL

### ISSUE THREAD

**Issue by jcvernaleo** [autonomoussoftware/metronome-wallet-desktop#32]
When starting the wallet up (v0.3.0 on ubuntu 16.04) the initial splash screen provides a link to see the license you need to accept but it just goes to the main metronome page rather than a license.

**Comment by gabmontes** [comment]
@jcvernaleo the license will be a PDF file stored in metronome.io website. It was not provided yet. Will keep the issue open until that file/link is provided.

cc/ @jordan-bloq
