### ISSUE TITLE
auction time units

### ISSUE THREAD

**Issue by jcvernaleo** [autonomoussoftware/metronome-wallet-desktop#33]
v0.3.0 on Ubuntu 16.04

The time units for the auction have the smallest units as `segs` which probably is supposed to be `secs`.

**Comment by pablen** [comment]
Duplicate of #20

**Comment by jcvernaleo** [comment]
Sorry about the dup.  I checked open issues before posting.  I figured with a release that was only about 16 hours old it was safe to not check closed issues :)
