### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by zuuritaly** [autonomoussoftware/metronome-wallet-desktop#347]
Hello!

I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Zuur

Graphic Designer

**Comment by ianaya89** [comment]
Hi @zuuritaly, thanks for your contribution. We already have a logo for this project but feel free to keep posting suggestions, feedback or anything you feel necessary!
