### ISSUE TITLE
Show friendly error if node returns invalid JSON response

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome-wallet-desktop#361]
![photo5298840014119086370](https://user-images.githubusercontent.com/32199587/41851510-b7e722ca-784d-11e8-852f-a4209e6e3927.jpg)

**Comment by jgarzik** [comment]
@Dareknotderek Please get OS version and wallet version from user

**Comment by ianaya89** [comment]
We already have an issue with this error (reported by Sentry).

**Comment by ianaya89** [comment]
Sentry already reported this issue so we have complete OS information.

https://sentry.io/bloq-inc/metronome-desktop-wallet/issues/588408464/

**Comment by gabmontes** [comment]
This error is originated in the Ethereum node. We should parse it and show a friendly error message instead.

**Comment by pablen** [comment]
In latest versions, known error messages are displayed with a more user-friendly verbiage and unknown error messages are displayed with a friendlier generic message.

Closing this issue.
