### ISSUE TITLE
"Contacting network" load screen 

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome-wallet-desktop#362]
Win 7, v 1.0.3

user experiences this screen, uninstalling/reinstalling unhelpful, off/on unhelpful. Sreen stays stuck like this. 

![photo5298784067875088726](https://user-images.githubusercontent.com/32199587/41855196-a56f115c-7857-11e8-81e4-eeebdc543c01.jpg)

**Comment by gabmontes** [comment]
@Dareknotderek user should update to latest version and try again.
