### ISSUE TITLE
Converter Error

### ISSUE THREAD

**Issue by Aleksmiki** [autonomoussoftware/metronome-wallet-desktop#363]
Whenever I want to trade Eth in Met, I get an error message. What can i do?
![unben12annt](https://user-images.githubusercontent.com/40579986/41873670-f4721d9e-78c5-11e8-92b2-cce0c6074d79.PNG)

**Comment by gabmontes** [comment]
@Aleksmiki do you have enough ETH to cover at least the transaction fee? Please confirm.

cc/ @Dareknotderek

**Comment by gabmontes** [comment]
Closing as no more information from OP was received.
