### ISSUE TITLE
Converter transaction displays zero (0) ETH received

### ISSUE THREAD

**Issue by jgarzik** [autonomoussoftware/metronome-wallet-desktop#374]
A converter transaction from MET to ETH shows zero ETH received.  The ETH **_is_** credited and the total balance is correct...  just not the transaction details.  txid 0x78256a6865751b559c000cfbe14c747540e045026ac4c56c10f7902c3f34d003

<img width="891" alt="screen shot 2018-06-26 at 7 15 30 pm" src="https://user-images.githubusercontent.com/494411/41944345-63c31afe-7975-11e8-8edb-d0674a0b3a4e.png">
<img width="415" alt="screen shot 2018-06-26 at 7 15 45 pm" src="https://user-images.githubusercontent.com/494411/41944346-63d32ee4-7975-11e8-8234-3acc3865ad15.png">

**Comment by jgarzik** [comment]
OS:  MacOSX 10.13.5
Wallet:  1.1.0

A rescan successfully fixes the display issue.

**Comment by gabmontes** [comment]
@jgarzik thanks! This is actually an issue that will fixed when #254 is implemented.

Closing this and tracking the progress there.
