### ISSUE TITLE
Failed Transaction

### ISSUE THREAD

**Issue by Kyscout** [autonomoussoftware/metronome-wallet-desktop#375]
I posted the following under another heading:
6.25.18:  I purchased MET tokens during the auction last night with indication the transaction was successful. Now my MET wallet says the transaction failed. What happened?!

6.27.18:  I would like to know why my transaction failed approximately 24 hours after the initial auction was completed. When I purchased the tokens, about 30 minutes before the auction ended, it stated it was successful. I have the transaction hash. Please advise asap!

I am still waiting on a reply... maybe I had under wrong heading.  Thank you!

**Comment by Kyscout** [comment]
When will this be addressed?

**Comment by gabmontes** [comment]
@Kyscout can you please provide details such as wallet version, operating system and transaction hash? Thanks.

**Comment by Kyscout** [comment]
Sure...as I mentioned above...it stated my transaction was successful 30 minutes prior to end of auction.  Then about 24 hours later it stated transaction had failed.

AMOUNT  0.95 ETH
TYPE  Auction
CONFIRMATIONS  69718
GAS USED  25231
TRANSACTION HASH  0xb294d5c76c778291b3d3b5c75fc2f259a98b8121a60645c6809d7c8dca6ce3be
BLOCK NUMBER  5848782

I was on the current MET wallet version at time of auction

operating system was Windows 7

Thank you!

**Comment by gabmontes** [comment]
@Kyscout the transaction you mentioned failed as it did not confirm before all tokens in the auction were sold. In fact, the transaction was finally marked as failed by the Ethereum network at 7/24 11:47:44 PM UTC.

The delay in showing the proper status in the wallet could have been related to connectivity issues of the wallet or network congestion of some other kind we could not identify.
