### ISSUE TITLE
Error: Operation timed out. Please try again later.

### ISSUE THREAD

**Issue by dman7** [autonomoussoftware/metronome-wallet-desktop#377]
When I try to send ETH from Metronome Wallet to a MetaMask address, I get a "Error: Operation timed out. Please try again later". Tried this June 27, 2018 and June 29, 2018. Gas Limit 53,000 and gwei 2. Metronome Desktop Wallet for Mac Version 1.1.1 (1.1.1)

<img width="452" alt="screen shot 2018-06-29 at 8 50 25 am" src="https://user-images.githubusercontent.com/964880/42102071-c743ad4a-7b79-11e8-9d2b-c1fb34f5cfbf.png">

**Comment by dman7** [comment]
The actual issue was that there wasn't enough balance to complete the transaction. I recommend updating the error message to be more clear.

**Comment by gabmontes** [comment]
@dman7 thanks for reporting that. We issues a fix on v1.1.2.
