### ISSUE TITLE
Unsurprisingly, building for Mac fails

### ISSUE THREAD

**Issue by reppolice** [autonomoussoftware/metronome-wallet-desktop#404]
I did not try to sign the executable, and did not get an executable either. I failed to build on current OSX both with slightly dated npm, as well as after fully updating/upgrading everything. Is there a point trying to fix this with not-too-enlightening- logs, or should we simply wait and see what the next release brings?
Thanks!

**Comment by ianaya89** [comment]
Hi @reppolice mac build should work. Actually, we are using it to distribute our apps.
Can you share logs and stack trace?

Thanks!

**Comment by gabmontes** [comment]
Closing as we received no feedback.
