### ISSUE TITLE
initial transaction does not show up in list

### ISSUE THREAD

**Issue by jcvernaleo** [autonomoussoftware/metronome-wallet-desktop#41]
Starting with a fresh wallet (so 0 balance) had someone send me some eth.  It did not show up in the balance until I closed and reopened.

Once reopened, the balance showed up but it does not appear in the tx list.

**Comment by jcvernaleo** [comment]
Screenshot as requested

![mtn](https://user-images.githubusercontent.com/768163/36327189-d11de594-132b-11e8-9a15-31930b427f47.png)

**Comment by pablen** [comment]
Related to #34
