### ISSUE TITLE
Wallet problems for windows 10

### ISSUE THREAD

**Issue by orlib** [autonomoussoftware/metronome-wallet-desktop#428]
Greetings Faced with such a problem, I can not restore the wallet with the help of recovery codes. Since in the pc version itself there is no such function. Many times deleted and reinstalled the wallet, but to no avail. It is not very convenient, since there is no important element. I take screenshots off
![screenshot_2](https://user-images.githubusercontent.com/41946119/52917022-955e7680-3310-11e9-95e0-1e4a27e3c393.png)

**Comment by gabmontes** [comment]
@orlib log into the wallet with your password, go to the Tools section and you will find the recovery option there.

**Comment by orlib** [comment]
how do i log in if not included?

>Понедельник, 18 февраля 2019, 5:10 +06:00 от Gabriel Montes <notifications@github.com>:
>
>@orlib log into the wallet with your password, go to the Tools section and you will find the recovery option there.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Hokumdar Hasanov

**Comment by gabmontes** [comment]
@orlib if you lost your password, close the wallet, remove all the file at `%APPDATA%\metronome-desktop-wallet` and open it again.

Be aware that doing so will remove *all* wallet settings and data. The only way to access your MET/ETH again is to recover the wallet from your 12-words passphrase.
