### ISSUE TITLE
Port tx failed message

### ISSUE THREAD

**Issue by jjkru382** [autonomoussoftware/metronome-wallet-desktop#446]
The port fail message doesn't show why tx failed.  It should say somewhere that it failed because you don't have ETC to cover gas costs. In order for me to see that is the issue I have to go to Morden network and click on port.  It needs to be clear when I am still on ropsten and trying to port to Morden.

**Comment by pablen** [comment]
Fixed in latest release. Port form is now disabled if the account has no funds in destination chain.
