### ISSUE TITLE
Properly identify good/bad auction buy or transfer txs

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome-wallet-desktop#46]
If i.e. buy fails and no tokens are returned back, the transaction row only displays:

![image](https://user-images.githubusercontent.com/2621975/36358663-ce5e5a0c-14f0-11e8-9a66-6c640a7285e7.png)

**Comment by ianaya89** [comment]
@gabmontes @pablen  I am testing some ways to do that: what do you think about this option:

- Show the user that got 0 MTN
- Show auction icon in red

<img width="875" alt="screen shot 2018-02-21 at 02 58 16" src="https://user-images.githubusercontent.com/3258966/36465325-472f30dc-16b3-11e8-954f-4873bb1e1451.png">

We can also add some error indicator in error receipt. What do you think?

**Comment by gabmontes** [comment]
Love it. Would add "purchase MTN in auction failed" in red below the numbers.
