### ISSUE TITLE
Error connection not open When converting from ETH to MET

### ISSUE THREAD

**Issue by GetITWorking** [autonomoussoftware/metronome-wallet-desktop#474]
When converting 0.416214 ETH to MET I get

**Error
connection not open
Try again**

Details :
Wallet Information
Version 1.4.2
Connected to Ethereum chain

Running on Linux

**Comment by zerbinidamata** [comment]
I am having the same issue to withdraw ETH

**Comment by GetITWorking** [comment]
Interesting,.. I think this is some sort of general connection issue,... because I also get errors while sync my Wallet. Could it be a fire wall issue? Or OS/browser AJAX query (Synchronous / Asynchronous)?

**Comment by zerbinidamata** [comment]
Yes, the sync always fails too.  I tried desktop (OS X) and Mobile(Android) both have same issue regarding sync and transactions, so I don't think is OS related.

Maybe a general connection issue with the wallet

**Comment by GetITWorking** [comment]
I'm just guessing,... I did not see any JS errors in the console log so its a bit odd, if this were a common issue I'm sure they would have fixed it by now, my bet is this works in most cases it must come down to the browser they use in the background for the app.. I don't know but I'm guessing they use React Native, which in turn uses a browser and on certain browser it has problem.

**Comment by GetITWorking** [comment]
Its all working for me now,... so looks like it was a server issue here... and it was not being able to connect or timing out.

**Comment by gabmontes** [comment]
This error is related to connectivity issues between the wallet and the supporting nodes, both of which were working fine. Our tests and monitoring/alerts setup did not catch anything.

The cause is mostly related to some intermediate gateways or networking equipment problems.

Thanks for reporting anyway.
