### ISSUE TITLE
Having Snyc issue

### ISSUE THREAD

**Issue by GetITWorking** [autonomoussoftware/metronome-wallet-desktop#480]
Hi Guys

Still having sync problems, when are you going to update your wallet software.

![image](https://user-images.githubusercontent.com/76945168/115667378-add9d980-a33d-11eb-8be8-90efddddf5d5.png)

**Comment by GetITWorking** [comment]
Now I'm having issues sending my ETH out to coinbase see :  

https://etherscan.io/tx/0x1c59d60da6b5c41c76c2a74105a432c8cfb78d80b20a0d605c25d7248d3faa32

**Comment by gabmontes** [comment]
@GetITWorking yes, we are working to fix the sync issues and hope to release a new version very soon.

**Comment by gabmontes** [comment]
Sync issues solved in v1.4.3 that was just released.
