### ISSUE TITLE
Could not connect to latest block

### ISSUE THREAD

**Issue by srwarren89** [autonomoussoftware/metronome-wallet-desktop#61]
When minimizing Metoronome it creates a pool of 'could not connect to latest block'. Cleans itself up quickly but the the in-app notifications should not accumulate so much. Version 0.3.0

**Comment by gabmontes** [comment]
@srwarren89 not able to reproduce in v0.5.0. Please upgrade and retry.

**Comment by ianaya89** [comment]
@srwarren89 Can you check if the issue is still happening
