### ISSUE TITLE
Unhandled error after bringing the app from minimize mode

### ISSUE THREAD

**Issue by srwarren89** [autonomoussoftware/metronome-wallet-desktop#64]
Minimized the app for a few hours where computer also went to sleep. At maximizing the app, it popped up the "Unhandled Error" message. 

"Unhandled Error
ReferenceError: event is not defined at BrowserWindow.<anonymous>
(/Applications/MetronomeWallet.app/Contents/Resources/app.asar/build/main/mainWindow.js:37:18)"

**Comment by gabmontes** [comment]
Fixed in 0.6.0.
