### ISSUE TITLE
Login screen does not display

### ISSUE THREAD

**Issue by srwarren89** [autonomoussoftware/metronome-wallet-desktop#68]
Bought some MTN, clicked the All View Tab, and the app crashed. Restarted laptop, when attempted to relaunch the app received unhandled error "Browser Can't Load". Then the login page appears, login, press send, and page appears blank

**Comment by ianaya89** [comment]
@srwarren89 What do you mean with the "All View Tab"?

**Comment by ianaya89** [comment]
Not able to reproduce in version `0.6.0`
