### ISSUE TITLE
Receiving wallet not showing transactions

### ISSUE THREAD

**Issue by srwarren89** [autonomoussoftware/metronome-wallet-desktop#69]
Sent ETH and MTN is not showing up in the receiving wallet. Sent 3 transactions to the same address. Receiving wallet does not see transactions under all or receiving tabs. Version 0.4.0

**Comment by filcap** [comment]
I'm also having some pending transactions last for a few days
<img width="905" alt="screen shot 2018-02-20 at 8 38 24 am" src="https://user-images.githubusercontent.com/24193763/36436579-84d42018-1619-11e8-8daf-8fd9578ecd07.png">

**Comment by srwarren89** [comment]
@ianaya89 refer to Fil's screenshot

**Comment by gabmontes** [comment]
Not able to replicate in v0.6 nor in upcoming v0.7. Closing for now.
