### ISSUE TITLE
Set gas/gas price of transactions

### ISSUE THREAD

**Issue by ianaya89** [autonomoussoftware/metronome-wallet-desktop#85]
Add support to gas price in UI & Main Process

**Comment by ianaya89** [comment]
@gabmontes

1. Should I include this in Auction, Converter and Send? 
2. Should I consider support for gas limit too?

**Comment by gabmontes** [comment]
Yes and yes. Perhaps as an "advanced" mini form that starts closed only showing defaults in a small font.
